# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import subprocess
from datetime import datetime
sys.path.insert(0, os.path.abspath('.'))
sys.path.append(os.path.abspath('_exts'))

# -- Project information -----------------------------------------------------
AUTHOR='tschinz'
try:
  VERSION = subprocess.check_output(["git", "describe", "--always"]).decode('UTF-8')
except:
  VERSION = 'v0.0'

project = 'Z-Notes'
copyright = f"Copyright 2004-{datetime.now().year}, tschinz \n"
date = subprocess.check_output(["git", "--no-pager", "log", "--oneline", "--pretty=format:'%h %ci'" ,"-n 1"]).decode('UTF-8')
author = AUTHOR

# The short X.Y version
version = VERSION
# The full version, including alpha/beta/rc tags
release = VERSION

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    "sphinx.ext.graphviz",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.todo",
    "sphinx.ext.extlinks",
    "sphinx.ext.githubpages",
    "sphinxcontrib.plantuml",
    "sphinx.ext.imgconverter",
    "sphinx_copybutton",
    "sphinxemoji.sphinxemoji",
    'sphinxcontrib.mermaid',
    "sphinxcontrib.wavedrom",
    "notfound.extension",
    'sphinx-prompt',
    "button",
    "tag",
]

# shinx panels config
panels_add_bootstrap_css = False

html_css_files = ["https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"]
panels_add_fontawesome_latex = True

# emoij style
#sphinxemoji_style = 'twemoji'

# external Links
extlinks = {'config_repo': ('https://github.com/tschinz/config/%s', None),
            'znotes_repo': ('https://github.com/tschinz/znotes/%s', None),
            'znotes_page': ('http://tschinz.github.io/znotes/%s', None),
            'pdf_view': ('https://github.com/tschinz/znotes/blob/master/%s', None),
            'pdf_dwld': ('https://github.com/tschinz/znotes/raw/master/%s', None),
            'pdfviewer': ('https://nbviewer.jupyter.org/%s', None),
            }

# Avoid warnings when different pages have the same titles
autosectionlabel_prefix_document = True

# Plant uml Jar file
plantuml = "java -jar -Djava.awt.headless=true " + os.path.abspath("." + os.sep + "_static" + os.sep + "jar" + os.sep + "plantuml.jar")

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
#source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
#pygments_style = 'pastie'
#pygments_style = 'monokai'
pygments_style = "sphinx"
#pygments_style = 'manni'
#pygments_style = 'default'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'sphinx_rtd_theme'
html_theme = "pydata_sphinx_theme"
# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}
html_favicon = 'img/favicon.png'
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_style = 'css/theme_overrides.css'

html_css_files = [
    'css/custom.css',
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
]

# Copybutton image path
#copybutton_image_path = 'img/copybutton.svg'

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
#html_sidebars = {}

# -- Options for LaTeX output ------------------------------------------------
latex_engine = 'xelatex'
latex_elements = {
    'fncychap': r'\usepackage[Bjornstrup]{fncychap}',
    'printindex': r'\footnotesize\raggedright\printindex',

    'papersize': 'a4paper',

    'pointsize': '10pt',
    'extraclassoptions': 'onecolumn,oneside',

    'fontpkg': r'''
        \setmainfont{DejaVu Serif}
        \setsansfont{DejaVu Sans}
        \setmonofont{DejaVu Sans Mono}
    ''',

    'preamble': r'''
        % !TeX program = xelatex
        \usepackage[utf8]{inputenc} % not needed utf8 by default
        \usepackage[titles]{tocloft}
        \cftsetpnumwidth {1.25cm}\cftsetrmarg{1.5cm}
        \setlength{\cftchapnumwidth}{0.75cm}
        \setlength{\cftsecindent}{\cftchapnumwidth}
        \setlength{\cftsecnumwidth}{1.25cm}
    ''',

    # Latex figure (float) alignment
    #
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'z-notes.tex', 'Z-Notes',
      AUTHOR, 'manual'),
]

latex_logo = 'img/znotes-logo.pdf'

# -- Extension configuration -------------------------------------------------
# -- Options for pydata-sphinx-theme -----------------------------------------
html_theme_options = {
  "icon_links": [
  {
    "name": "GitHub",
    "url": "https://github.com/tschinz/znotes",
    "icon": "fa-brands fa-square-github",
    "type": "fontawesome",
    },
    {
    "name": "Twitter",
    "url": "https://twitter.com/tschinz",
    "icon": "fa-brands fa-square-twitter",
    "type": "fontawesome",
    }
  ],
  "navbar_start": ["navbar-logo"],
  "navbar_center": ["navbar-nav"],
  #"navbar_end": ["theme-switcher", "navbar-icon-links"],
  "navbar_persistent": ["search-button"],
  "navbar_align": "content",
  "show_prev_next": False,
  "show_nav_level": 2,
  "navigation_depth": 2,
  "show_toc_level": 2,
  "collapse_navigation": True, # default
  "navigation_depth": 4, # default
  "navigation_with_keys": True, # default
  "search_bar_text": "Don't panic, search",
  "use_edit_page_button": True,
  "footer_start": ["navbar-logo"],
  "footer_end": ["footer"],
}

html_sidebars = {
    "index": ["search-field", "index-sidebar"],
    "**": ["search-field", "sidebar-nav-bs"],
}

html_context = {
    #'css_files': [
    #    '_static/css/theme_overrides.css',  # override wide tables in RTD theme
    #    '_static/css/copy_button.css',      # override copybutton on code-block
    #],
    "github_user": "tschinz",
    "github_repo": "znotes",
    "github_version": "master",
    "doc_path": "src",
    "default_mode": "light",
}

html_show_sourcelink = False
html_logo = 'img/logo.svg'
html_title = 'Z-Notes'
# This is a temporary fix for wavedrom
offline_skin_js_path = "_static/js/default.js"
offline_wavedrom_js_path = "_static/js/wavedrom.min.js"

# Option for linkcheck
linkcheck_anchors=False

# Activate todo within the documentation (extension sphinx.ext.todo)
todo_include_todos = True

# -- RST Epilog ----------------------------------------------------------
rst_epilog = """
.. |folder| image:: /img/icons/folder.svg
.. |file| image:: /img/icons/file.svg
.. |sign-check| image:: /img/icons/success.svg

.. |upload| image:: /img/icons/upload.svg
.. |download| image:: /img/icons/download.svg
.. |expand| image:: /img/icons/expand.svg
.. |minimize| image:: /img/icons/minimize.svg

.. |arrow-up| image:: /img/icons/arrow-up.svg
.. |arrow-down| image:: /img/icons/arrow-down.svg
.. |arrow-left| image:: /img/icons/arrow-left.svg
.. |arrow-right| image:: /img/icons/arrow-right.svg

.. |+| image:: /img/icons/add.svg

.. |star5| image:: /img/icons/star-5.svg
.. |star4| image:: /img/icons/star-4.svg
.. |star3| image:: /img/icons/star-3.svg
.. |star2| image:: /img/icons/star-2.svg
.. |star1| image:: /img/icons/star-1.svg
.. |star| image:: /img/icons/star.svg

.. |en| image:: /img/icons/uk.svg
.. |ch| image:: /img/icons/switzerland.svg
.. |de| image:: /img/icons/germany.svg
.. |china| image:: /img/icons/china.svg
.. |uk| image:: /img/icons/uk.svg
.. |usa| image:: /img/icons/usa.svg
.. |it| image:: /img/icons/italy.svg
.. |jp| image:: /img/icons/japan.svg
.. |fr| image:: /img/icons/france.svg

.. |linux| image:: /img/icons/linux.svg
.. |mac| image:: /img/icons/apple.svg
.. |win| image:: /img/icons/windows.svg

.. |word| image:: /img/icons/word.svg
.. |excel| image:: /img/icons/excel.svg
.. |onenote| image:: /img/icons/onenote.svg
.. |outlook| image:: /img/icons/outlook.svg
"""
